version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/native-addon-go"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/native-addon-rust"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/wasm-rust"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/wasm-go"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/src/wasm-go"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/src/native-addon-go"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/src/wasm-rust"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/src/native-addon-rust"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
