FROM node:latest AS build
CMD ["yarn", "run", "start"]
EXPOSE 3000
WORKDIR /home/frotend
ENV PATH="/root/.cargo/bin:${PATH}"
RUN apt-get -qq update &&\
    apt-get install -y -q build-essential curl golang-go libpcap-dev &&\
    curl https://sh.rustup.rs -sSf | sh -s -- -y
COPY ./frontend .
RUN yarn --ignore-engines
WORKDIR /home/backend
COPY ./backend .
RUN yarn --ignore-engines &&\
    yarn run generate-postgresql-types &&\
    yarn run generate-mongodb-types &&\
    yarn run build

