FROM oven/bun:latest AS build
ENV PATH="/root/.cargo/bin:${PATH}"
WORKDIR /home/backend
RUN apt-get -qq update &&\
    apt-get install -y -q build-essential curl golang-go &&\
    curl https://sh.rustup.rs -sSf | sh -s -- -y
COPY . .
RUN bun install --yarn &&\
    bun run bun-generate-types &&\
    bun run bun-build 
FROM oven/bun:latest
EXPOSE 3000
WORKDIR /home/backend
CMD ["bun", "index.js"]
COPY --from=build /home/backend/destination /home/backend
