plugins:
  - serverless-offline
service: zsbrybnik
app: zsbrybnik
org: zsbrybnik
provider:
  name: aws
  runtime: nodejs16.x

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  zsbrybnik:
    handler: destination/source/test.handler
    events:
      - http:
          path: /{any+}
          method: ANY
