kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: zsb
data:
  .dockerconfigjson: {{ .Values.containers.imagePullSecrets }}
