apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.metadata.selector }}
  ports:
    - port: {{ .Values.services.port }}
      targetPort: {{ .Values.services.targetPort }}
  type: {{ .Values.services.type }}
